//------------------------------------------------------------------
//-- File generated by RobustVerilog parser
//-- RobustVerilog version 1.5g (limited free version) Jul 5 2011
//-- Invoked Wed Mar 28 12:55:29 2012
//-- Source file: prgen_rand.v
//-- Parent file: axi_master_single.v
//-- Project directory: C:/Users/MARIOS/Desktop/VLSI/RobustVerilog_free1.5_win/RobustVerilog_free1.5_win/examples/axi_master/trunk/run/
//-- Target directory: out/
//-- Command flags: ..\..\..\..\robust.exe ../robust_axi_master.pro -gui 
//-- www.provartec.com/edatools ... info@provartec.com
//------------------------------------------------------------------




  
function integer rand_chance;
      input [31:0] chance_true;

      begin
     if (chance_true > 100)
       begin
          $display("RAND_CHANCE-E-: fatal error, rand_chance called with percent chance larger than 100.\tTime: %0d ns", $time);
          $finish;
       end
     rand_chance = (rand(1,100) <= chance_true);
      end
endfunction // rand_chance


function integer rand;
      input [31:0] min;
      input [31:0] max;

      integer      range;
      begin
     if (min > max)
       begin
          $display("RAND-E-: fatal error, rand was called with min larger than max.\tTime: %0d ns", $time);
          $finish;
       end

     range = (max - min) + 1;
     if (range == 0) range = -1;
     rand  = min + ($random % range); 
      end
endfunction // rand


function integer align;
      input [31:0]  num;
      input [31:0]  align_size;
      
      begin
         align = num - (num % align_size);
      end
endfunction


function integer rand_align;
      input [31:0] min;
      input [31:0] max;
      input [31:0] align_val;

      begin
         rand_align = rand(min, max);
         
         if (rand_align > align_val)
           rand_align = align(rand_align, align_val);
      end
endfunction



